version: 2
jobs:
  tests:

    working_directory: ~/build

    docker:
      - image: maven:3.6.3-openjdk-14-slim

    steps:

      - checkout

      - restore_cache:
          key: organizze-api-client-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - save_cache:
          paths:
            - ~/.m2
          key: organizze-api-client-{{ checksum "pom.xml" }}

      - run:
          name: Test
          command: mvn package -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

workflows:
  version: 2
  main:
    jobs:
      - tests
