version: 2.1

jobs:
  test:
    docker:
      image: maven:3.6.3-openjdk-14-slim
    steps:
      - checkout
      - run:
          name: Tests
          command: |
            mvn clean test

workflows:
  version: 2
  workflow:
    jobs:
      - test
