version: 2
jobs:
  build:

    working_directory: ~/build

    docker:
      - image: maven:3.6.3-openjdk-14-slim

    steps:

      - checkout

      - restore_cache:
          key: organizze-api-clien-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: organizze-api-clien-{{ checksum "pom.xml" }}

      - run: mvn package